name: Publish to Docs

on:
  push:
    branches: [test]  # Change to main after mainnet is live and we publish masa-oracle to main (if desired)
    paths:
      - '.github/workflows/publish-to-docs.yaml'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine/git

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Copy Readme
      run: |
        mkdir pub-docs
        cp docs/welcome-to-masa.md pub-docs/
        cp -r docs/ai-node-operator pub-docs/
        cp -r docs/ai-oracle-node pub-docs/
        cp -r docs/guides-and-tutorials pub-docs/

    - name: Push to target repository
      uses: actions/checkout@v4
      with:
        repository: masa-finance/docs
        path: docs
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy files to target repository
      run: |
        cp -r pub-docs/. docs/masa-oracle/
        cd docs
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add masa-oracle/
        git commit -m "Update docs from source repository"
        git push
